[package]
name = "aoc"
version = "0.1.0"
authors = ["Matthew Maurer <matthew.r.maurer@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
sscanf = "0.1"
bitvec = "0.22"
